# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Github Java ci flow

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn clean install

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build docker image
      run: docker build -t mamonov/github-java-ci-flow .
    - name: Publish image to docker hub
      run: docker push mamonov/github-java-ci-flow:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull Image from docker hub
        run: docker pull mamonov/github-java-ci-flow:latest
      - name: Delete old container
        run: docker rm -f github-java-ci-flow
      - name: Run docker container
        run: docker run -d -p 80:8080 --name github-java-ci-flow mamonov/github-java-ci-flow:latest